# https://rook.github.io/docs/rook/master/object.html
#
apiVersion: ceph.rook.io/v1beta1
kind: ObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPool:
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  gateway:
    type: s3
    sslCertificateRef: tls-secret
    port: 80
    securePort: 443
    instances: 1
    allNodes: false
